name: Go Test and Security

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run unit tests
      run: go test -v ./...

    - name: Run integration tests (if API key is set)
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      run: |
        if [ -n "$DEEPSEEK_API_KEY" ]; then
          echo "API key found, running integration tests"
          go test -v -tags=integration ./...
        else
          echo "No API key set, skipping integration tests"
        fi

    - name: Run gosec security scan
      run: ~/go/bin/gosec ./...